name: Hot CVEs List

on:
  workflow_dispatch:
  schedule:
      - cron: '0 */6 * * *'

jobs:
  ScheduledRun:
    runs-on: ubuntu-latest
        
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Running the HOT CVEs generator script
      run: |
        cd /home/runner/work/cve/cve
        pip install requests
        python .github/getTrending.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check for changes and commit if necessary
      run: |
        cd /home/runner/work/cve/cve
        git config --global user.name 'CVE-BOT'
        git config --global user.email 'cve@codepwn.win'
        git remote set-url origin https://github-actions[bot]:$GITHUB_TOKEN@github.com/0xMarcio/cve.git
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Trending CVEs update $(date +'%Y-%m-%d %H:%M') :robot:"
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
